### ISSUE TITLE
Android back button closes app

### ISSUE THREAD

**Issue by gjhughes** [FidelLimited/rn-sdk#8] opened 2019-08-06 14:38 UTC
Pressing the android back button when Fidel modal is visible causing app to close, would expect modal to just be dismissed.

Can be reproduced by running the example app in the `rn-sdk` repo. 

![fidel2](https://user-images.githubusercontent.com/18194213/62549261-17f7d580-b860-11e9-824a-e2b1e1bfb9b1.gif)

**Comment by c0derabbit** [comment] 2019-08-06 15:25
@gjhughes thanks, we'll have a look at this!

**Comment by gjhughes** [comment] 2019-08-14 13:30
Additional info as requested:

1. We are running react-native version `0.59.1` on our app.
2. I didn't make any changes to the example app in the repo to demo the issue above.  I just cloned the repo, installed and then ran the app as it is.

**Comment by ccorneliu** [comment] 2019-08-14 13:32
Thank you for reporting this, @gjhughes. Can you please help me with some more information:

1. Which version of the Fidel React Native SDK did you try out?
2. What Android Studio version did you use?
3. What Emulator did you use? What API level?
4. How are errors handled in the example project that you have? I'm interested in this part (from App.js):

```javascript
onLinkButtonPress() {
    Fidel.openForm((error, result) => {
      if (error) {
        console.debug(error);
      } else {
        console.info(result);
      }
    });
  }
```

When the user closes the Fidel SDK UI, it replies with an error. In an older version of the example app, we used to handle the errors with `console.error(...)` which crashed the app. This is fixed in the latest example project. Just wondering if that's not the case for you.

Thank you!

**Comment by gjhughes** [comment] 2019-08-14 14:05
Hey, sure..

1. 1.0.5
2. Android Studio 3.3.2
3. Tested on API 27 and 29, same issue on both*
4. I do recalls seeing the previous version with `console.error` but I'm using the latest version now which handles the error the same way as your example above.

Hope that helps, let me know if you need any further info.

* we are seeing this on real devices, too

**Comment by ccorneliu** [comment] 2019-08-14 18:24
@gjhughes Can you please remove the `node_modules` folder in your `example` project and attach a zip of the project here? If it doesn't work to attach, please use a service like https://www.wetransfer.com to send a link to your project here.

I can't reproduce the issue. I tried with all the exact versions you mention here. I might be missing something else, so it would be easier to look at what you have.

Thank you!

**Comment by SMJ93** [comment] 2019-08-15 11:14
Hi @ccorneliu, I am also getting the same issue with your example project: https://github.com/FidelLimited/rn-sdk/tree/master/example.

I cloned the repo, ran `npm install` and then ran the Android app using `react-native run-android`.

**Closed** 2019-08-26 20:17 UTC
Labels: bug

**Comment by SMJ93** [comment] 2019-08-27 09:23
@ccorneliu thanks for fixing, when will it be published to npm?

**Comment by c0derabbit** [comment] 2019-08-27 18:09
@SMJ93 it's updated! 🚀 We'll set up some auto-publishing soon.
