### ISSUE TITLE
Exception on Loading Logo Image

### ISSUE THREAD

**Issue by jahskee** [FidelLimited/rn-sdk#7] opened 2019-07-30 23:27 UTC
![Fidel_Exception](https://user-images.githubusercontent.com/10620946/62172377-05314e00-b300-11e9-89cb-28d4f4e98b75.png)

**Comment by jahskee** [comment] 2019-07-31 00:55
Can I ask what Android family of emulators you are using? Seems like this issue does not appear in Galaxy Nexus.

**Comment by jahskee** [comment] 2019-07-31 01:46
- This happens to Android API 28 & 29, when I close the card linking window, this error shows up.

- The card link works perfectly on Android API 22-27

**Comment by gjhughes** [comment] 2019-08-05 10:37
Having the same issue... is there any progress / update on this?

**Comment by ccorneliu** [comment] 2019-08-14 19:19
The error in the attached image seems to be a problem with adapting the banner image. Can you please attach the complete code that you have for setting the Fidel SDK options (with `Fidel.setOptions`).

Please make sure you resolve the image before you set it as the `bannerImage`. Check the example here:
https://github.com/FidelLimited/rn-sdk#how-to-use-fidels-react-native-sdk

```javascript
const myImage = require('./images/fdl_test_banner.png');
const resolveAssetSource = require('react-native/Libraries/Image/resolveAssetSource');
const resolvedImage = resolveAssetSource(myImage);

Fidel.setOptions({ bannerImage: resolvedImage });
```

**Comment by ccorneliu** [comment] 2019-08-14 19:24
I have not been successful in reproducing the close button crash. Can you please follow issue #8 for progress on this.

If you can share an example project in which you experience this issue, that would be great. Please follow the instructions in my comment about this: https://github.com/FidelLimited/rn-sdk/issues/8#issuecomment-521361865

**Comment by c0derabbit** [comment] 2019-08-30 16:40
@jahskee @gjhughes can you please verify if upgrading to v1.1.0 fixes this one?

**Comment by jahskee** [comment] 2019-09-01 16:04
I upgraded to 1.1.0 and the error does not appear. thanks!

**Comment by c0derabbit** [comment] 2019-09-01 19:53
That's good news, closing in that case :)

**Closed by c0derabbit** 2019-09-01 19:53 UTC
Labels: bug
