### ISSUE TITLE
Test credit cards are invalid

### ISSUE THREAD

**Issue by jahskee** [FidelLimited/rn-sdk#5] opened 2019-07-21 09:41 UTC
I tried to use the test cc posted in Fidel doc, but it returns an invalid error.
Please advise.

-Jaizon

**Comment by c0derabbit** [comment] 2019-07-23 07:49
hi @jahskee, could you please provide some more info? what test card number did you try?

**Comment by jahskee** [comment] 2019-07-23 21:57
Hi c0derabbit,

The test cc # and exp mm/yy was marked red.
 
![testCCIssue](https://user-images.githubusercontent.com/10620946/61750360-31ceee00-ad73-11e9-888f-428063c6df73.png)

**Comment by c0derabbit** [comment] 2019-07-30 14:54
I can't reproduce, there must be something other than the ccn that causes the whole form to appear as invalid. We'll try to investigate this.

**Comment by c0derabbit** [comment] 2019-08-22 13:50
@jahskee I've found some inconsistencies in Android. A quick look suggests that we might be Luhn checking test card numbers. I'll verify and be back!

**Comment by c0derabbit** [comment] 2019-08-22 14:17
@ccorneliu this looks like something in the native SDKs. Can you please check card validation there, and whether we correctly determine test / live environment?

**Comment by jahskee** [comment] 2019-09-01 16:08
Looks like, I don't see this issue anymore.

**Comment by c0derabbit** [comment] 2019-09-01 19:56
Me neither. Closing as most probably solved in 1.1.0.

**Closed by c0derabbit** 2019-09-01 19:56 UTC
Labels: bug
